server:
  port: 7070 # 当前项目所在的服务端口号

spring:
  application:
    name: deepseek-doctor # 定义当前项目的应用名称
  profiles:
    active: dev

# 配置日志级别为info
logging:
  level:
    root: info

# MyBatisPlus 的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
  mapper-locations: classpath*:/mappers/*.xml